version: 2.1

jobs:
  build-and-push:
    docker:
      - image: docker:20.10.9
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Push Docker Image
          command: |
            docker build -t nurisa/docker-tutorial:latest -f Dockerfile .
            echo "$DOCKERHUB_PASSWORD" | docker login --username nurisa --password-stdin
            docker push nurisa/docker-tutorial:latest
  pull-and-deploy:
    docker:
      - image: circleci/node:14
    steps:
      - run:
         name: Install SSH And Configure
         command: |
              echo "$SSH_PRIVATE_KEY" | base64 -d > ./privateKey.pem
              chmod 400 privateKey.pem
      - run:
         name: Pull Image and Deploy
         command: |
            ssh -o "StrictHostKeyChecking=no" -i ./privateKey.pem ubuntu@$HOST '
            sudo docker pull nurisa/docker-tutorial:latest
            sudo docker run -d -p 80:8080 nurisa/docker-tutorial:latest 
           '

workflows:
  deploy:
    jobs:
      - build-and-push:
          filters:
            branches:
              only: master
      - pull-and-deploy:
          requires:
            - build-and-push
          filters:
            branches:
              only: master